// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type DLQEvent struct {
	ID           string         `json:"id"`
	TopicName    string         `json:"topicName"`
	PartitionID  int            `json:"partitionId"`
	KafkaOffset  int            `json:"kafkaOffset"`
	Payload      map[string]any `json:"payload"`
	ErrorType    string         `json:"errorType"`
	ErrorMessage string         `json:"errorMessage"`
	RetryCount   int            `json:"retryCount"`
	Status       string         `json:"status"`
	ProducerID   *string        `json:"producerId,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	LastRetryAt  *time.Time     `json:"lastRetryAt,omitempty"`
}

type DLQStats struct {
	Pending   int `json:"pending"`
	Retrying  int `json:"retrying"`
	Retried   int `json:"retried"`
	Discarded int `json:"discarded"`
	Total     int `json:"total"`
}

type LagPoint struct {
	Timestamp time.Time `json:"timestamp"`
	Lag       int       `json:"lag"`
}

type LagUpdate struct {
	Topic         string          `json:"topic"`
	ConsumerGroup string          `json:"consumerGroup"`
	TotalLag      int             `json:"totalLag"`
	Partitions    []*PartitionLag `json:"partitions"`
	Timestamp     time.Time       `json:"timestamp"`
	IsAlert       bool            `json:"isAlert"`
}

type Mutation struct {
}

type PartitionLag struct {
	Topic           string `json:"topic"`
	Partition       int    `json:"partition"`
	ConsumerGroup   string `json:"consumerGroup"`
	LatestOffset    int    `json:"latestOffset"`
	CommittedOffset int    `json:"committedOffset"`
	Lag             int    `json:"lag"`
}

type PartitionOffset struct {
	Partition int `json:"partition"`
	Offset    int `json:"offset"`
}

type Query struct {
}

type RetryResult struct {
	Success bool   `json:"success"`
	EventID string `json:"eventId"`
	Message string `json:"message"`
}

type Schema struct {
	ID         string         `json:"id"`
	TopicName  string         `json:"topicName"`
	Version    int            `json:"version"`
	SchemaJSON map[string]any `json:"schemaJson"`
	IsActive   bool           `json:"isActive"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type Subscription struct {
}

type Topic struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description,omitempty"`
	Partitions        int                `json:"partitions"`
	ReplicationFactor int                `json:"replicationFactor"`
	CreatedAt         time.Time          `json:"createdAt"`
	LatestOffsets     []*PartitionOffset `json:"latestOffsets,omitempty"`
}

type TopologyEdge struct {
	Source    string   `json:"source"`
	Target    string   `json:"target"`
	EventRate *float64 `json:"eventRate,omitempty"`
}

type TopologyGraph struct {
	Nodes []*TopologyNode `json:"nodes"`
	Edges []*TopologyEdge `json:"edges"`
}

type TopologyNode struct {
	ID       string         `json:"id"`
	Type     string         `json:"type"`
	Label    string         `json:"label"`
	Metadata map[string]any `json:"metadata,omitempty"`
}
